# Generated by Django 5.2.4 on 2025-07-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
