# Generated by Django 5.2.4 on 2025-07-20 11:36

import s3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0002_uploadedfile_content_type_uploadedfile_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=s3.models.upload_to_s3_unique),
        ),
    ]
