# Generated by Django 5.2.4 on 2025-07-20 11:43

import s3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0003_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=s3.models.upload_to_s3_unique, validators=[s3.models.validate_file_size]),
        ),
    ]
