# Generated by Django 5.2.4 on 2025-07-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0005_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
